# Generated by Django 4.2.2 on 2024-01-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_contact',
            field=models.IntegerField(),
        ),
    ]
