# Generated by Django 4.2.2 on 2024-01-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_company_company_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_contact',
            field=models.CharField(max_length=10),
        ),
    ]
