# Generated by Django 4.2.2 on 2024-01-17 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.offer'),
        ),
    ]
