# Generated by Django 4.2.2 on 2024-01-31 05:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_product_colors_remove_product_sizes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_detail',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
