# Generated by Django 5.0.1 on 2024-02-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_order_is_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='contact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='fname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='lname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
