# Generated by Django 5.0.1 on 2024-02-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_billingaddress_contact_billingaddress_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='contact',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='fname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='lname',
            field=models.CharField(max_length=100),
        ),
    ]
