# Generated by Django 5.0.1 on 2024-02-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_delivered',
        ),
    ]
